    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br>

        <div class="field vkfadressen_autoid required">
            <label for="vkfadressen_autoid" class="label"><span><?php /* @escapeNotVerified */ echo __('Vkfadressen Autoid') ?></span></label>
            <div class="control">
                <input type="text" name="vkfadressen_autoid" id="vkfadressen_autoid" title="<?php /* @escapeNotVerified */ echo __('Vkfadressen Autoid') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
            </div>
        </div>
    </fieldset>
